package enclaveproto

// Note: All structs that start with "Enclave" are used for communication between the API service and the enclave.
type EnclavePrepareKEKRequest struct {
	// Wrapped Master key generated by KMS
	MasterKey string `json:"master_key"`
	// Wrapped Table Salt generated by KMS
	TableSalt string `json:"table_salt"`
	// Client's ephemeral public key
	ClientEphemeralPublicKey string `json:"client_ephemeral_public_key"`
}

// Note: All structs that start with "Enclave" are used for communication between the API service and the enclave.
type EnclavePrepareKEKResponse struct {
	// x25519 public key of the enclave, Base64-encoded
	EnclavePubKey string `json:"enclave_public_key"`
	// Unwrapped Master key generated by KMS, Base64-encoded
	MasterKey string `json:"master_key"`
	// Unwrapped Table Salt generated by KMS, Base64-encoded
	TableSalt string `json:"table_salt"`
	// Nonce used for NaCl box encryption, Base64-encoded
	Nonce string `json:"nonce"`
}
