package enclaveproto

type PrepareKEKRequest struct {
	// Wrapped Master key generated by KMS
	MasterKey []byte `json:"master_key"`
	// Wrapped Table Salt generated by KMS
	TableSalt []byte `json:"table_salt"`
	// Client's ephemeral public key
	ClientEphemeralPublicKey []byte `json:"client_ephemeral_public_key"`
}

type PrepareKEKResponse struct {
	// x25519 public key of the enclave
	EnclavePubKey []byte `json:"enclave_public_key"`
	// Unwrapped Master key generated by KMS
	MasterKey []byte `json:"master_key"`
	// Unwrapped Table Salt generated by KMS
	TableSalt []byte `json:"table_salt"`
	// Nonce used for NaCl box encryption
	Nonce []byte `json:"nonce"`
}
